# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-18 14:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_address_physical', models.CharField(max_length=45)),
                ('node_address_logical', models.CharField(max_length=45)),
                ('node_active', models.IntegerField()),
                ('node_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'node',
            },
        ),
        migrations.CreateModel(
            name='NodeProbeStatusLog',
            fields=[
                ('probe_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('probe_time', models.DateTimeField(default=django.utils.timezone.now)),
                ('node_reply', models.IntegerField()),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.Node')),
            ],
            options={
                'db_table': 'node_probe_status_log',
            },
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('port_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_number', models.IntegerField()),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.Node')),
            ],
            options={
                'db_table': 'port',
            },
        ),
        migrations.CreateModel(
            name='PortConfiguration',
            fields=[
                ('port_configuration_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_configuration_file', models.CharField(max_length=250)),
                ('port_configuration_status', models.CharField(blank=True, max_length=45, null=True)),
                ('data_format', models.CharField(max_length=45)),
                ('port_configuration_version', models.IntegerField()),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('port_type', models.CharField(max_length=45)),
                ('data_type', models.CharField(max_length=45)),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.Port')),
            ],
            options={
                'db_table': 'port_configuration',
            },
        ),
        migrations.CreateModel(
            name='PortValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port_value', models.CharField(max_length=45)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('node', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.Node')),
                ('port', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.Port')),
            ],
            options={
                'db_table': 'port_value',
            },
        ),
    ]
