# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 09:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='command',
            fields=[
                ('command_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_code', models.IntegerField()),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('command_code_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.command')),
            ],
        ),
        migrations.CreateModel(
            name='commandcode',
            fields=[
                ('command_code_id', models.AutoField(primary_key=True, serialize=False)),
                ('command_code', models.IntegerField()),
                ('command_description', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='node',
            fields=[
                ('node_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_address_physical', models.IntegerField()),
                ('node_address_logical', models.IntegerField(default=0)),
                ('node_active', models.BooleanField(default=True)),
                ('node_name', models.CharField(blank=True, default='null', max_length=45, null=True)),
            ],
            options={
                'db_table': 'node',
            },
        ),
        migrations.CreateModel(
            name='nodeconfiguration',
            fields=[
                ('node_configuration_id', models.AutoField(primary_key=True, serialize=False)),
                ('node_configuration', models.CharField(blank=True, max_length=250, null=True)),
                ('node_configuration_status', models.BooleanField(default=False)),
                ('node_configuration_version', models.IntegerField(default=0)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('node_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.node')),
            ],
            options={
                'db_table': 'port_configuration',
            },
        ),
        migrations.CreateModel(
            name='nodeport',
            fields=[
                ('port_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_number', models.IntegerField()),
                ('data_type', models.CharField(default='int', max_length=45)),
                ('port_type', models.CharField(default='actuator', max_length=45)),
                ('port_mode', models.CharField(default='digital', max_length=45)),
                ('device_attached', models.CharField(default='LED', max_length=45)),
                ('node_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.node')),
            ],
            options={
                'db_table': 'port',
            },
        ),
        migrations.CreateModel(
            name='portvalue',
            fields=[
                ('port_value_id', models.AutoField(primary_key=True, serialize=False)),
                ('port_value', models.CharField(max_length=45)),
                ('time_stamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('port_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.nodeport')),
            ],
            options={
                'db_table': 'port_value',
            },
        ),
        migrations.CreateModel(
            name='probestatuslog',
            fields=[
                ('probe_status_id', models.AutoField(primary_key=True, serialize=False)),
                ('probe_time', models.DateTimeField(blank=True, null=True)),
                ('node_reply', models.BooleanField(default=False)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
                ('node_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.node')),
            ],
            options={
                'db_table': 'node_probe_status_log',
            },
        ),
        migrations.CreateModel(
            name='startupconfiguration',
            fields=[
                ('startup_configuration_id', models.AutoField(primary_key=True, serialize=False)),
                ('part_number', models.IntegerField(default=0)),
                ('startup_configuration', models.CharField(max_length=500)),
                ('time_stamp', models.DateTimeField(blank=True, null=True)),
                ('node_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.node')),
            ],
        ),
        migrations.CreateModel(
            name='startupconfigurationlog',
            fields=[
                ('startup_config_log_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply_time', models.DateTimeField(blank=True, null=True)),
                ('send_time', models.DateTimeField(blank=True, null=True)),
                ('node_reply', models.BooleanField(default=False)),
                ('startup_configuration_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.startupconfiguration')),
            ],
        ),
        migrations.AddField(
            model_name='command',
            name='node_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='reconwsan.node'),
        ),
    ]
