# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-01 09:29
from __future__ import unicode_literals

from django.db import migrations

def forwards_func(apps, schema_editor):
    # We get the model from the versioned app registry;
    # if we directly import it, it'll be the wrong version
    CommandCode = apps.get_model("reconwsan", "commandcode")
    db_alias = schema_editor.connection.alias
    CommandCode.objects.using(db_alias).bulk_create([
        CommandCode(command_code = 0, command_description = "Probe Node Status"),
        CommandCode(command_code = 1, command_description = "Probe Node Status Reply"),
        CommandCode(command_code = 2, command_description = "Configure Network Details"),
        CommandCode(command_code = 3, command_description = "Configure Network Acknowledge"),
        CommandCode(command_code = 6, command_description = "Acknowledge Node Startup Configuration Receive"),
        CommandCode(command_code = 7, command_description = "Cannot Access SD Card"),
        CommandCode(command_code = 8, command_description = "Sent Node Startup Configuration"),
        CommandCode(command_code = 9, command_description = "Maximum Attempts for Startup Configuration Reached"),
        CommandCode(command_code = 16, command_description = "No SD Card Read"),
        CommandCode(command_code = 11, command_description = "Successful Node Startup from SD Card"),
        CommandCode(command_code = 15, command_description = "Send Port Data"),
        CommandCode(command_code = 0, command_description = "Default"),
    ])


class Migration(migrations.Migration):

    dependencies = [
        ('reconwsan', '0001_initial'),
    ]

    operations = [
    	migrations.RunPython(forwards_func),
    ]
